server:
  port: 8088


spring:
  datasource:
    username: root
    password: 246855
    url: jdbc:mysql://localhost:3306/gsafety?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath*:com/littlexx/shiro/demo/dao/mapping/*.xml
  type-aliases-package: com.littlexx.shiro.demo.model
