server:
  port: 8088


spring:
  datasource:
    username: root
    password: 246855
    url: jdbc:mysql://localhost:3306/gsafety?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        min-idle: 0
        max-idle: 8


mybatis-plus:
  mapper-locations: classpath*:com/littlexx/shiro/demo/dao/mapping/*.xml
  type-aliases-package: com.littlexx.shiro.demo.model
